/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package amsystem;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Mohammad
 */
public class AddStudent extends javax.swing.JFrame {
 

    public AddStudent(){
        initComponents();
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxDept = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxSem = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        Deletebutn = new javax.swing.JButton();
        Editbutn = new javax.swing.JButton();
        showbtn = new javax.swing.JButton();
        Savebutn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblshow = new javax.swing.JTable();
        Cancelbtn = new javax.swing.JButton();

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setText("Semester:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add New student");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Father's name:");

        txtName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setText("       Id:");

        txtID.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setText("              Name:              ");

        txtContact.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setText("Contact:");

        txtFName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText("               Email:");

        txtEmail.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setText("Semester:");

        jComboBoxDept.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jComboBoxDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDept.setToolTipText("select");
        jComboBoxDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDeptActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setText("Department:");

        jComboBoxSem.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jComboBoxSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSem.setToolTipText("select");
        jComboBoxSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSemActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setText("Address:");

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        Deletebutn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        Deletebutn.setText("Delete");
        Deletebutn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebutnActionPerformed(evt);
            }
        });

        Editbutn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        Editbutn.setText("Update");
        Editbutn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbutnActionPerformed(evt);
            }
        });

        showbtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        showbtn.setText("Show");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });

        Savebutn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        Savebutn.setText("Insert");
        Savebutn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebutnActionPerformed(evt);
            }
        });

        tblshow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Father's name", "Contact", "Email", "Department", "Semester", "Address"
            }
        ));
        jScrollPane3.setViewportView(tblshow);

        Cancelbtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Deletebutn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Editbutn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Savebutn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel5)
                        .addGap(33, 33, 33)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxSem, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxDept, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxSem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxDept, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Savebutn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deletebutn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editbutn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDeptActionPerformed

    private void jComboBoxSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSemActionPerformed
 
    private void SavebutnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebutnActionPerformed
       AddStudent std = new AddStudent();
      
        if(txtID.getText().trim().length()==0)
      {
          JOptionPane.showMessageDialog(this, "Please Enter Your ID");
          txtID.setText("");
      }
       else if(txtName.getText().trim().length()==0)
      {
          JOptionPane.showMessageDialog(this, "Please Enter Your Name");
          txtName.setText("");
         
      }else if(txtFName.getText().trim().length()==0)
      {
          JOptionPane.showMessageDialog(this, "Please Enter Your Father Name");
          txtFName.setText("");
      }else if(txtContact.getText().trim().length()==0)
      {
           JOptionPane.showMessageDialog(this, "Please Enter Your Contact");
          txtContact.setText("");     
       }else if(jTextAreaAddress.getText().trim().length()==0)
       {
           
        JOptionPane.showMessageDialog(this, "Please Enter Your Address");
          jTextAreaAddress.setText(""); 
       }else if(jComboBoxDept.getSelectedItem().equals("Select"))
       {
            JOptionPane.showMessageDialog(this, "Please Enter Your Department");
          jComboBoxDept.setSelectedItem("Select");
       }else if(jComboBoxSem.getSelectedItem().equals("Select"))
       {
            JOptionPane.showMessageDialog(this, "Please Enter Your Semester");
          jComboBoxSem.setSelectedItem("Select");
       }else
       {
              try {
                  std.fillStudentsJtable(tblshow, "");
                  try {
                       int id = Integer.parseInt(txtID.getText());
                  String name = txtName.getText();
                  String fname = txtFName.getText();
                  int contact = Integer.parseInt(txtContact.getText());
                  String dept = (String) jComboBoxDept.getSelectedItem();
                  String sem = (String) jComboBoxSem.getSelectedItem();
                  String address = jTextAreaAddress.getText();
                  String email = txtEmail.getText();
                 
                  
             
                     Class.forName("com.mysql.cj.jdbc.Driver");
                  Connection con = (java.sql.Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/attendence_ms","root","");
                 PreparedStatement ps =con.prepareStatement("insert into studentb(id, Name, fName, Contact, Dept, Sem, Address, Email) value(?,?,?,?,?,?,?,?)");  
                 ps.setInt(1, id);
                 ps.setString(2, name);
                 ps.setString(3, fname);
                 ps.setInt(4, contact);
                 ps.setString(5, dept);
                 ps.setString(6, sem);
                  ps.setString(7, address);
                 ps.setString(8, email);
                 
                 ps.executeUpdate();
                 JOptionPane.showMessageDialog(this, "Your Data Is Saved Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
           
        } catch (NumberFormatException nfe) {
            System.out.println("NumberFormat Exception: invalid input string");
        }
              } catch (SQLException  | ClassNotFoundException ex) {
                  Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
              }
          
          
             
       }
    }//GEN-LAST:event_SavebutnActionPerformed

    private void EditbutnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbutnActionPerformed

        PreparedStatement ps = null;
         Connection con;
         
   
         if(txtID.getText().trim().length()==0)
      {
          JOptionPane.showMessageDialog(this, "Please Enter Your ID");
          txtID.setText("");
      }
       else if(txtName.getText().trim().length()==0)
      {
          JOptionPane.showMessageDialog(this, "Please Enter Your Name");
          txtName.setText("");
         
      }else if(txtFName.getText().trim().length()==0)
      {
          JOptionPane.showMessageDialog(this, "Please Enter Your Father Name");
          txtFName.setText("");
      }else if(txtContact.getText().trim().length()==0)
      {
           JOptionPane.showMessageDialog(this, "Please Enter Your Contact");
          txtContact.setText("");     
       }else if(jTextAreaAddress.getText().trim().length()==0)
       {
           
        JOptionPane.showMessageDialog(this, "Please Enter Your Address");
          jTextAreaAddress.setText(""); 
       }else if(jComboBoxDept.getSelectedItem().equals("Select"))
       {
            JOptionPane.showMessageDialog(this, "Please Enter Your Department");
          jComboBoxDept.setSelectedItem("Select");
       }else if(jComboBoxSem.getSelectedItem().equals("Select"))
       {
            JOptionPane.showMessageDialog(this, "Please Enter Your Semester");
          jComboBoxSem.setSelectedItem("Select");
       }else
       {
        try {
            
            try {
                 con = (java.sql.Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/attendence_ms","root","");
            
             
            ps = con.prepareStatement("update studentb set  Name=?, fName=?, Contact=?, Dept=?, Sem=?, Address=? , Email=? WHERE id=?");
     
                 
                 ps.setString(1, txtName.getText());
                 ps.setString(2, txtFName.getText());
                 ps.setInt(3, Integer.parseInt(txtContact.getText()));
                 ps.setString(4, (String) jComboBoxDept.getSelectedItem());
                 ps.setString(5, (String) jComboBoxSem.getSelectedItem());
                  ps.setString(6, jTextAreaAddress.getText());
                 ps.setString(7, txtEmail.getText());
                  ps.setInt(8, Integer.parseInt(txtID.getText()));
          
                 ps.executeUpdate();
                 JOptionPane.showMessageDialog(this, "Your Data Is Updated Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
           
        } catch (NumberFormatException nfe) {
            System.out.println("NumberFormat Exception: invalid input string");
        }
           
        } catch (SQLException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        
        
        
        
    }//GEN-LAST:event_EditbutnActionPerformed

    private void DeletebutnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebutnActionPerformed
       
        PreparedStatement ps = null;
         Connection con;
        if(!txtID.getText().equals(""))
        {   
            try {
                 con = (java.sql.Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/attendence_ms","root","");
                ps = con.prepareStatement("DELETE FROM studentb WHERE id=?");
                int id = Integer.parseInt(txtID.getText());
                ps.setInt(1, id);
                 ps.executeUpdate();
                 JOptionPane.showMessageDialog(this, "Your Data Is Deleted!");
            } catch (SQLException ex) {
                Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
     
        }else
        {
            JOptionPane.showMessageDialog(this, "Your Data Not Deleted : No Id To Delete!");
        }
    }//GEN-LAST:event_DeletebutnActionPerformed
      public void deleteAllRowFromTable(JTable table)
      {
      DefaultTableModel model = (DefaultTableModel)table.getModel();
         Object[] row;
        
      }
    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
   AddStudent std = new AddStudent();
  
        try {
            std.fillStudentsJtable(tblshow, "");
        } catch (SQLException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
   
    }//GEN-LAST:event_showbtnActionPerformed

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
     System.exit(0);
    }//GEN-LAST:event_CancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }
    
    public void fillStudentsJtable(JTable table, String ValueToSearch) throws SQLException
    {
       PreparedStatement ps = null;
         Connection con;
         con = (java.sql.Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/attendence_ms","root","");
            ps = con.prepareStatement("SELECT * FROM `studentb` WHERE CONCAT('Name','FName','Contact','Dept','Sem','Address','Email')LIKE ?");
         ps.setString(1, "%"+ValueToSearch+"%");
         ResultSet rs = ps.executeQuery();
         DefaultTableModel model = (DefaultTableModel)table.getModel();
         Object[] row;
         while(rs.next())
         {
             row = new Object[8];
             row[0] = rs.getInt(1);
             row[1] = rs.getString(2);
             row[2] = rs.getString(3);
             row[3] = rs.getString(4);
             row[4] = rs.getString(5);
             row[5] = rs.getString(6);
             row[6] = rs.getString(7);
             row[7] = rs.getString(8);
             model.addRow(row);
             
         }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JButton Deletebutn;
    private javax.swing.JButton Editbutn;
    private javax.swing.JButton Savebutn;
    private javax.swing.JComboBox<String> jComboBoxDept;
    private javax.swing.JComboBox<String> jComboBoxSem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JButton showbtn;
    private javax.swing.JTable tblshow;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
